<?php
/** Phase 12 read-only intelligence for Search campaigns only. */
namespace WNQ\Services;

use WNQ\Models\PpcMemory;

if (!defined('ABSPATH')) exit;

final class PpcAdvancedSearchService
{
    public function report(string $client_id, string $customer_id, array $search, array $ads, array $keywords, bool $refresh = false): array
    {
        $memory_available=true;try { $memory = PpcMemory::context($client_id, $customer_id); } catch (\Throwable $e) { $memory_available=false;$memory=['memories'=>[],'feedback'=>[],'rules'=>[]]; }
        $modules = [];
        foreach (['anomalies','quality_score'] as $name) {
            try { $modules[$name] = $name === 'anomalies' ? $this->anomalies($customer_id,$refresh) : $this->qualityScore($customer_id,$refresh); }
            catch (\Throwable $e) { $modules[$name] = self::unavailable(ucwords(str_replace('_',' ',$name)).' is temporarily unavailable.'); }
        }
        $local = [
            'ngrams'=>fn()=>empty($search['available'])?self::unavailable('N-gram intelligence is unavailable because search-term evidence did not load.'):self::ngrams((array)($search['terms']??[]),$memory),
            'routing'=>fn()=>empty($search['available'])||empty($keywords['available'])?self::unavailable('Routing intelligence requires both search-term and keyword evidence.'):self::routing((array)($search['terms']??[]),(array)($keywords['keywords']??[]),(array)($keywords['negatives']??[]),$memory),
            'messaging'=>fn()=>empty($search['available'])||empty($ads['available'])?self::unavailable('Messaging-gap intelligence requires both search-term and RSA evidence.'):self::messaging((array)($search['terms']??[]),(array)($ads['ads']??[]),(array)($ads['claim_config']??[]),(array)($ads['website_evidence']??[]),$memory),
        ];
        foreach ($local as $name=>$builder) {
            try { $modules[$name]=$builder(); } catch (\Throwable $e) { $modules[$name]=self::unavailable(ucwords($name).' is temporarily unavailable.'); }
        }
        $modules['memory']=['available'=>$memory_available,'status'=>$memory_available?'ready':'unavailable','message'=>$memory_available?'':'Persistent PPC memory is temporarily unavailable.','memories'=>(array)$memory['memories'],'feedback'=>(array)$memory['feedback'],'rules'=>(array)$memory['rules'],'period'=>'Durable client history'];
        return $modules;
    }

    private function anomalies(string $customer_id, bool $refresh): array
    {
        $key='wnq_ppc_anomaly_'.md5($customer_id);
        if(!$refresh && is_array($cached=get_transient($key))) return $cached;
        $end=current_datetime()->modify('-1 day')->format('Y-m-d');
        $start=current_datetime()->modify('-35 days')->format('Y-m-d');
        $query=new GoogleAdsQueryService();
        $rows=$query->select($customer_id,"SELECT campaign.id, campaign.name, segments.date, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.search_impression_share, metrics.search_budget_lost_impression_share, metrics.search_rank_lost_impression_share FROM campaign WHERE campaign.advertising_channel_type = 'SEARCH' AND campaign.status = 'ENABLED' AND segments.date BETWEEN '{$start}' AND '{$end}' ORDER BY campaign.id, segments.date");
        if($query->errors()) return self::unavailable('Campaign anomaly evidence is unavailable.');
        $result=self::analyzeAnomalies($rows,$start,$end); set_transient($key,$result,15*MINUTE_IN_SECONDS); return $result;
    }

    public static function analyzeAnomalies(array $rows,string $start,string $end): array
    {
        $campaigns=[];
        foreach($rows as $row){$c=(array)($row['campaign']??[]);$m=(array)($row['metrics']??[]);$date=(string)($row['segments']['date']??'');$id=(string)($c['id']??'');if($id===''||$date==='')continue;$campaigns[$id]['name']=sanitize_text_field((string)($c['name']??'Campaign'));$campaigns[$id]['days'][$date]=['impressions'=>(int)($m['impressions']??0),'clicks'=>(int)($m['clicks']??0),'cost'=>((float)($m['costMicros']??0))/1000000,'conversions'=>(float)($m['conversions']??0),'search_is'=>self::nullable($m['searchImpressionShare']??null),'lost_budget'=>self::nullable($m['searchBudgetLostImpressionShare']??null),'lost_rank'=>self::nullable($m['searchRankLostImpressionShare']??null)];}
        $findings=[];$summaries=[];
        foreach($campaigns as $id=>$campaign){$weeks=[];for($w=0;$w<5;$w++){$week=[];$from=(new \DateTimeImmutable($start))->modify('+'.($w*7).' days');for($d=0;$d<7;$d++)$week[]=$campaign['days'][$from->modify("+{$d} days")->format('Y-m-d')]??self::zeroDay();$weeks[]=self::week($week);}
            $current=$weeks[4];$baseline=array_slice($weeks,0,4);$anomalies=[];
            $defs=['spend'=>['min'=>10,'den'=>'spend'],'clicks'=>['min'=>15,'den'=>'clicks'],'cpc'=>['min'=>20,'den'=>'clicks'],'ctr'=>['min'=>200,'den'=>'impressions'],'conversions'=>['min'=>20,'den'=>'clicks'],'conversion_rate'=>['min'=>20,'den'=>'clicks'],'cpa'=>['min'=>3,'den'=>'conversions'],'search_is'=>['min'=>200,'den'=>'impressions'],'lost_is_budget'=>['min'=>200,'den'=>'impressions'],'lost_is_rank'=>['min'=>200,'den'=>'impressions']];
            foreach($defs as $metric=>$guard){$den=(float)($current[$guard['den']]??0);$baseline_den=array_sum(array_column($baseline,$guard['den']))/4;$values=array_column($baseline,$metric);if(($current[$metric]??null)===null||in_array(null,$values,true))continue;$mean=array_sum($values)/max(1,count($values));$sd=self::sd($values,$mean);$value=(float)$current[$metric];$relative=abs($value-$mean)/max(abs($mean),.01);$z=$sd>.0001?abs($value-$mean)/$sd:($relative>=.5?3:0);if($den<$guard['min']||$baseline_den<$guard['min']||$relative<.30||$z<2.5)continue;$direction=$value>$mean?'up':'down';$anomalies[]=['metric'=>$metric,'direction'=>$direction,'current'=>$value,'baseline'=>$mean,'relative_change'=>$mean!=0?($value-$mean)/abs($mean):null,'z_score'=>$z,'minimum_data'=>$den,'guard'=>$guard['min']];}
            if($anomalies){$summary=['campaign_id'=>$id,'campaign'=>$campaign['name'],'current'=>$current,'anomalies'=>$anomalies,'period'=>'Last 7 complete days vs prior four 7-day windows'];$summaries[]=$summary;foreach($anomalies as $a)$findings[]=['severity'=>'warning','title'=>'Search campaign anomaly: '.self::label($a['metric']).' '.$a['direction'],'evidence'=>$campaign['name'].' moved from a weekly baseline of '.self::formatMetric($a['metric'],$a['baseline']).' to '.self::formatMetric($a['metric'],$a['current']).'. This is an anomaly, not a diagnosed cause.','period'=>$summary['period'],'action'=>'Investigate auction conditions, query mix, tracking, budgets, and recent changes before drawing a conclusion.','confidence'=>min(.92,.62+min(.25,$a['z_score']/20)),'campaign_id'=>$id,'campaign'=>$campaign['name'],'section'=>'ppc-anomalies'];}
        }
        return ['available'=>true,'status'=>'ready','campaigns'=>$summaries,'findings'=>$findings,'period'=>'Last 7 complete days vs prior 28 complete days','method'=>'Four campaign-specific weekly baselines; ≥30% movement, ≥2.5 standard deviations, and metric-specific minimum volume.'];
    }

    public static function ngrams(array $terms,array $memory=[]):array
    {
        $grams=[];
        foreach($terms as $term){$tokens=array_values(array_filter(explode(' ',self::normalize((string)($term['query']??'')))));foreach([1,2,3] as $n){$seen=[];for($i=0;$i<=count($tokens)-$n;$i++){$text=implode(' ',array_slice($tokens,$i,$n));if(isset($seen[$text]))continue;$seen[$text]=1;$key=$n.'|'.$text;$grams[$key]??=['ngram'=>$text,'size'=>$n,'queries'=>0,'impressions'=>0,'clicks'=>0,'cost'=>0.0,'conversions'=>0.0];$grams[$key]['queries']++;foreach(['impressions','clicks'] as $m)$grams[$key][$m]+=(int)($term[$m]??0);foreach(['cost','conversions'] as $m)$grams[$key][$m]+=(float)($term[$m]??0);}}}
        foreach($grams as &$g){$g['cost']=round($g['cost'],2);$g['conversions']=round($g['conversions'],2);$g['conversion_rate']=$g['clicks']?round($g['conversions']/$g['clicks'],4):0;$g['cpa']=$g['conversions']?round($g['cost']/$g['conversions'],2):0;$g['classification']='monitor';if($g['queries']>=3&&$g['clicks']>=8&&$g['conversions']==0)$g['classification']='waste_investigation';elseif($g['queries']>=2&&$g['clicks']>=5&&$g['conversions']>=2)$g['classification']='high_performing_intent';$rules=PpcMemory::rulesForText($g['ngram'],$memory);$g['client_rule_context']=array_map(static fn($r)=>(string)$r['content'],$rules);}unset($g);
        $grams=array_values(array_filter($grams,static fn($g)=>$g['queries']>=2));usort($grams,static fn($a,$b)=>$b['cost']<=>$a['cost']);$findings=[];$waste=array_values(array_filter($grams,static fn($g)=>$g['classification']==='waste_investigation'));$wins=array_values(array_filter($grams,static fn($g)=>$g['classification']==='high_performing_intent'));if($waste)$findings[]=['severity'=>'warning','title'=>'Recurring n-gram waste patterns','evidence'=>count($waste).' recurring 1–3 word pattern(s) meet conservative no-conversion review thresholds.','period'=>'Last 30 days','action'=>'Review the underlying queries, intent, and client rules. Do not add negatives automatically.','confidence'=>.78,'campaign_id'=>'','section'=>'ppc-ngrams'];if($wins)$findings[]=['severity'=>'opportunity','title'=>'High-performing search intent patterns','evidence'=>count($wins).' recurring pattern(s) produced at least two conversions with sufficient clicks.','period'=>'Last 30 days','action'=>'Review keyword coverage, routing, and RSA alignment for these themes.','confidence'=>.8,'campaign_id'=>'','section'=>'ppc-ngrams'];return ['available'=>true,'status'=>'ready','items'=>array_slice($grams,0,250),'waste'=>$waste,'winners'=>$wins,'findings'=>$findings,'period'=>'Last 30 days'];
    }

    public static function routing(array $terms,array $keywords,array $negatives,array $memory=[]):array
    {
        $cases=[];
        foreach($terms as $term){if((int)($term['clicks']??0)<2)continue;$query=self::normalize((string)($term['query']??''));$currentScore=self::similarity($query,self::normalize((string)($term['keyword']??'')));$best=null;
            foreach($keywords as $keyword){if((string)($keyword['ad_group_id']??'')===(string)($term['ad_group_id']??''))continue;$candidate=self::normalize((string)($keyword['keyword']??''));if($candidate===''||!str_contains(' '.$query.' ',' '.$candidate.' '))continue;$score=self::similarity($query,$candidate);if($score<.6||$score<$currentScore+.15)continue;if(!$best||$score>$best['score'])$best=['score'=>$score,'keyword'=>$keyword];}
            if(!$best)continue;$negative_matches=PpcNegativeInventoryService::conflicts([['criterion_id'=>'route-check','keyword'=>$query,'match_type'=>'exact','campaign_id'=>(string)$best['keyword']['campaign_id'],'campaign'=>(string)$best['keyword']['campaign'],'ad_group_id'=>(string)$best['keyword']['ad_group_id'],'ad_group'=>(string)$best['keyword']['ad_group']]],$negatives);$rules=PpcMemory::rulesForText($query,$memory);
            $cases[]=['query'=>(string)$term['query'],'campaign_id'=>(string)$term['campaign_id'],'campaign'=>(string)$term['campaign'],'ad_group_id'=>(string)$term['ad_group_id'],'ad_group'=>(string)$term['ad_group'],'matched_keyword'=>(string)$term['keyword'],'better_campaign_id'=>(string)$best['keyword']['campaign_id'],'better_campaign'=>(string)$best['keyword']['campaign'],'better_ad_group_id'=>(string)$best['keyword']['ad_group_id'],'better_ad_group'=>(string)$best['keyword']['ad_group'],'better_keyword'=>(string)$best['keyword']['keyword'],'similarity'=>round($best['score'],2),'existing_negative_context'=>count($negative_matches),'client_rule_context'=>array_map(static fn($r)=>(string)$r['content'],$rules),'clicks'=>(int)$term['clicks'],'cost'=>(float)$term['cost'],'conversions'=>(float)$term['conversions']];}
        usort($cases,static fn($a,$b)=>$b['cost']<=>$a['cost']);$findings=$cases?[['severity'=>'warning','title'=>'Possible Search query routing leakage','evidence'=>count($cases).' query route(s) may have more relevant enabled keyword coverage in another ad group or campaign.','period'=>'Last 30 days + current keyword/negative configuration','action'=>'Inspect intent, match behavior, and existing negatives. Treat each route as an investigation only.','confidence'=>.7,'campaign_id'=>(string)$cases[0]['campaign_id'],'campaign'=>(string)$cases[0]['campaign'],'section'=>'ppc-routing']]:[];return ['available'=>true,'status'=>'ready','cases'=>array_slice($cases,0,100),'findings'=>$findings,'period'=>'Last 30 days + current configuration'];
    }

    public static function messaging(array $terms,array $ads,array $claims,array $website,array $memory=[]):array
    {
        $themes=self::ngrams($terms,$memory)['winners']??[];$gaps=[];$approved=' ';foreach($claims as $claim)$approved.=self::normalize((string)($claim['claim']??'')).' ';
        foreach($themes as $theme){$needle=self::normalize((string)$theme['ngram']);if(strlen($needle)<4)continue;$routes=[];foreach($terms as $term)if(str_contains(' '.self::normalize((string)($term['query']??'')).' ',' '.$needle.' ')&&(float)($term['conversions']??0)>0)$routes[(string)($term['campaign_id']??'').'|'.(string)($term['ad_group_id']??'')]=['campaign_id'=>(string)($term['campaign_id']??''),'campaign'=>(string)($term['campaign']??''),'ad_group_id'=>(string)($term['ad_group_id']??''),'ad_group'=>(string)($term['ad_group']??'')];foreach($routes as $route){$relevant=array_filter($ads,static fn($ad)=>($ad['status']??'')==='enabled'&&(string)($ad['campaign_id']??'')===$route['campaign_id']&&(string)($ad['ad_group_id']??'')===$route['ad_group_id']);$copy=' ';foreach($relevant as $ad)foreach(array_merge((array)($ad['headlines']??[]),(array)($ad['descriptions']??[])) as $asset)$copy.=self::normalize((string)($asset['text']??'')).' ';if(str_contains($copy,$needle))continue;$source='';foreach((array)($website['pages']??[]) as $page)if(str_contains((string)($page['text']??''),$needle)){$source=(string)($page['url']??'');break;}$verified=$source!==''||str_contains($approved,$needle);$gaps[]=['theme'=>$needle]+$route+['queries'=>(int)$theme['queries'],'clicks'=>(int)$theme['clicks'],'conversions'=>(float)$theme['conversions'],'cpa'=>(float)$theme['cpa'],'claim_verified'=>$verified,'source'=>$source,'recommendation'=>$verified?'Consider source-grounded RSA messaging around “'.$needle.'” in '.$route['ad_group'].'; a human must approve the exact wording.':'Theme is absent from this ad group’s active RSA copy, but no new messaging is recommended until the claim/theme is verified against an approved client source.'];}}
        $verified=array_values(array_filter($gaps,static fn($g)=>$g['claim_verified']));$findings=$gaps?[['severity'=>'opportunity','title'=>'Search intent to RSA messaging gaps','evidence'=>count($gaps).' high-performing recurring theme(s) are missing from active RSA copy; '.count($verified).' have supporting client-source evidence.','period'=>'Last 30 days + current enabled RSA configuration','action'=>'Review source-backed themes and draft exact copy only after factual verification. No ad is changed here.','confidence'=>.74,'campaign_id'=>'','section'=>'ppc-messaging']]:[];return ['available'=>true,'status'=>empty($website['available'])?'partial':'ready','message'=>empty($website['available'])?'Website evidence is unavailable; unverified themes remain blocked from copy recommendations.':'','gaps'=>$gaps,'findings'=>$findings,'period'=>'Last 30 days + current configuration'];
    }

    private function qualityScore(string $customer_id,bool $refresh):array
    {
        $key='wnq_ppc_qs_'.md5($customer_id);if(!$refresh&&is_array($cached=get_transient($key)))return $cached;$end=current_datetime()->modify('-1 day')->format('Y-m-d');$start=current_datetime()->modify('-30 days')->format('Y-m-d');$query=new GoogleAdsQueryService();$rows=$query->select($customer_id,"SELECT campaign.id, campaign.name, ad_group.id, ad_group.name, ad_group_criterion.criterion_id, ad_group_criterion.keyword.text, ad_group_criterion.keyword.match_type, ad_group_criterion.quality_info.quality_score, ad_group_criterion.quality_info.search_predicted_ctr, ad_group_criterion.quality_info.creative_quality_score, ad_group_criterion.quality_info.post_click_quality_score, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.search_impression_share FROM keyword_view WHERE campaign.advertising_channel_type = 'SEARCH' AND campaign.status = 'ENABLED' AND ad_group.status = 'ENABLED' AND ad_group_criterion.status = 'ENABLED' AND segments.date BETWEEN '{$start}' AND '{$end}' LIMIT 10000");if($query->errors())return self::unavailable('Quality Score evidence is unavailable.');$items=[];
        foreach($rows as $row){$q=(array)($row['adGroupCriterion']['qualityInfo']??[]);$m=(array)($row['metrics']??[]);$score=(int)($q['qualityScore']??0);$cost=((float)($m['costMicros']??0))/1000000;$conversions=(float)($m['conversions']??0);$search_is=self::nullable($m['searchImpressionShare']??null);$significance=$cost+((int)($m['impressions']??0)/100)+($conversions*25)+($search_is===null?0:((1-$search_is)*(int)($m['impressions']??0)/100));$issues=array_filter(['expected_ctr'=>self::bucket($q['searchPredictedCtr']??''),'ad_relevance'=>self::bucket($q['creativeQualityScore']??''),'landing_page_experience'=>self::bucket($q['postClickQualityScore']??'')],static fn($v)=>$v==='below_average');if(!$issues||($cost<10&&(int)($m['clicks']??0)<10&&(int)($m['impressions']??0)<200))continue;$items[]=['campaign_id'=>(string)($row['campaign']['id']??''),'campaign'=>sanitize_text_field((string)($row['campaign']['name']??'')),'ad_group_id'=>(string)($row['adGroup']['id']??''),'ad_group'=>sanitize_text_field((string)($row['adGroup']['name']??'')),'criterion_id'=>(string)($row['adGroupCriterion']['criterionId']??''),'keyword'=>sanitize_text_field((string)($row['adGroupCriterion']['keyword']['text']??'')),'quality_score'=>$score?:null,'expected_ctr'=>self::bucket($q['searchPredictedCtr']??''),'ad_relevance'=>self::bucket($q['creativeQualityScore']??''),'landing_page_experience'=>self::bucket($q['postClickQualityScore']??''),'impressions'=>(int)($m['impressions']??0),'clicks'=>(int)($m['clicks']??0),'cost'=>round($cost,2),'conversions'=>round($conversions,2),'cpa'=>$conversions?round($cost/$conversions,2):0,'search_is'=>$search_is,'economic_significance'=>round($significance,2),'issues'=>array_keys($issues)];}
        usort($items,static fn($a,$b)=>$b['economic_significance']<=>$a['economic_significance']);$findings=$items?[['severity'=>'opportunity','title'=>'Economically significant keyword quality issues','evidence'=>count($items).' enabled Search keyword(s) have a below-average quality component and sufficient traffic or spend to merit investigation.','period'=>'Last 30 complete days + current Quality Score components','action'=>'Investigate the below-average component alongside spend, conversions, CPA, and impression share. Low Quality Score alone is not a change recommendation.','confidence'=>.82,'campaign_id'=>(string)$items[0]['campaign_id'],'campaign'=>(string)$items[0]['campaign'],'section'=>'ppc-quality-score']]:[];$result=['available'=>true,'status'=>'ready','items'=>$items,'findings'=>$findings,'period'=>'Last 30 complete days + current Quality Score components'];set_transient($key,$result,15*MINUTE_IN_SECONDS);return $result;
    }

    private static function week(array $days):array{$sum=['impressions'=>0,'clicks'=>0,'spend'=>0.0,'conversions'=>0.0];$weighted=['search_is'=>[0,0],'lost_is_budget'=>[0,0],'lost_is_rank'=>[0,0]];foreach($days as $d){$sum['impressions']+=$d['impressions'];$sum['clicks']+=$d['clicks'];$sum['spend']+=$d['cost'];$sum['conversions']+=$d['conversions'];foreach(['search_is','lost_budget','lost_rank'] as $m){$out=$m==='lost_budget'?'lost_is_budget':($m==='lost_rank'?'lost_is_rank':$m);if($d[$m]!==null){$weighted[$out][0]+=$d[$m]*max(1,$d['impressions']);$weighted[$out][1]+=max(1,$d['impressions']);}}}$sum['cpc']=$sum['clicks']?$sum['spend']/$sum['clicks']:0;$sum['ctr']=$sum['impressions']?$sum['clicks']/$sum['impressions']:0;$sum['conversion_rate']=$sum['clicks']?$sum['conversions']/$sum['clicks']:0;$sum['cpa']=$sum['conversions']?$sum['spend']/$sum['conversions']:0;foreach($weighted as $k=>$v)$sum[$k]=$v[1]?$v[0]/$v[1]:null;return $sum;}
    private static function zeroDay():array{return ['impressions'=>0,'clicks'=>0,'cost'=>0.0,'conversions'=>0.0,'search_is'=>null,'lost_budget'=>null,'lost_rank'=>null];}
    private static function sd(array $values,float $mean):float{return sqrt(array_sum(array_map(static fn($v)=>(($v-$mean)**2),$values))/max(1,count($values)));}
    private static function normalize(string $v):string{return trim(preg_replace('/\s+/',' ',preg_replace('/[^a-z0-9]+/i',' ',strtolower($v)))??'');}
    private static function similarity(string $a,string $b):float{$aa=array_unique(array_filter(explode(' ',$a)));$bb=array_unique(array_filter(explode(' ',$b)));if(!$aa||!$bb)return 0;return count(array_intersect($aa,$bb))/count(array_unique(array_merge($aa,$bb)));}
    private static function bucket($v):string{return strtolower(sanitize_key((string)$v))?:'unknown';}
    private static function nullable($v):?float{return is_numeric($v)?(float)$v:null;}
    private static function label(string $v):string{return ucwords(str_replace('_',' ',$v));}
    private static function formatMetric(string $metric,float $v):string{if(in_array($metric,['spend','cpc','cpa'],true))return '$'.number_format($v,2);if(in_array($metric,['ctr','conversion_rate','search_is','lost_is_budget','lost_is_rank'],true))return number_format($v*100,1).'%';return number_format($v,2);}
    private static function unavailable(string $message):array{return ['available'=>false,'status'=>'unavailable','message'=>$message,'items'=>[],'cases'=>[],'gaps'=>[],'campaigns'=>[],'findings'=>[]];}
}
