<?php
/** Evidence-first PPC investigation and prioritization. */
namespace WNQ\Services;
if (!defined('ABSPATH')) exit;

final class PpcInvestigationService
{
    public static function build(string $client_id,string $customer_id,array $dashboard,array $search,array $ads,array $keywords,array $advanced=[]):array
    {
        $findings=array_merge((array)($dashboard['findings']??[]),(array)($search['findings']??[]),(array)($ads['findings']??[]),(array)($keywords['findings']??[]));
        foreach (['anomalies','ngrams','routing','messaging','quality_score'] as $module) $findings=array_merge($findings,(array)($advanced[$module]['findings']??[]));
        $shared=count(array_filter((array)($dashboard['budget_analysis']['campaigns']??[]),static fn($c)=>!empty($c['shared_budget'])));
        if($shared)$findings[]=['severity'=>'opportunity','title'=>'Shared budget requires grouped analysis','evidence'=>$shared.' campaign(s) use shared budgets, so campaign-level pacing cannot be interpreted independently.','period'=>'Current configuration','action'=>'Evaluate every campaign attached to the shared budget before recommending allocation or increases.','confidence'=>.98,'campaign_id'=>''];
        $cases=[];foreach($findings as $finding){if(($finding['severity']??'')==='healthy')continue;$direct=self::direct((string)($finding['title']??''));$data=self::dataConfidence($finding,$dashboard,$search,$ads,$keywords);$rec=min((float)($finding['confidence']??.5),$data);
            $cases[]=['severity'=>$finding['severity'],'problem'=>(string)$finding['title'],'observation'=>(string)$finding['evidence'],'period'=>(string)$finding['period'],'hypotheses'=>self::hypotheses((string)$finding['title']),'root_cause_status'=>$direct?'confirmed':'unconfirmed','root_cause'=>$direct?(string)$finding['evidence']:'Available evidence identifies a risk, but does not yet prove a single root cause.','recommendation'=>(string)$finding['action'],'historical_context'=>self::history($finding,(array)($advanced['memory']['memories']??[])),'data_confidence'=>$data,'recommendation_confidence'=>$rec,'minimum_data_note'=>$data<.7?'Minimum-data safeguard active: gather more evidence before acting.':'Available evidence meets the current review threshold.','campaign_id'=>(string)($finding['campaign_id']??''),'section'=>(string)($finding['section']??'ppc-attention')];}
        usort($cases,static fn($a,$b)=>self::rank($a['severity'])<=>self::rank($b['severity'])?:$b['recommendation_confidence']<=>$a['recommendation_confidence']);
        $priority=self::priority($cases,$dashboard);$result=['available'=>true,'status'=>'ready','cases'=>$cases,'summary'=>self::summary($cases),'priority'=>$priority,'generated_at'=>current_time('mysql')];
        update_option('wnq_ppc_priority_snapshot_'.md5($client_id),['client_id'=>$client_id,'customer_id'=>$customer_id,'priority'=>$priority,'summary'=>$result['summary'],'generated_at'=>$result['generated_at']],false);return $result;
    }
    public static function snapshot(string $client_id):array{$v=get_option('wnq_ppc_priority_snapshot_'.md5($client_id),[]);return is_array($v)?$v:[];}
    private static function priority(array $cases,array $dashboard):array{$top=$cases[0]['severity']??'healthy';$tier=['critical'=>1,'warning'=>2,'opportunity'=>3,'healthy'=>5][$top]??4;$shared=count(array_filter((array)($dashboard['budget_analysis']['campaigns']??[]),static fn($c)=>!empty($c['shared_budget'])));return ['tier'=>$tier,'label'=>['','Critical','High priority','This week','Monitor','No action'][$tier],'shared_budgets'=>$shared,'case_count'=>count($cases)];}
    private static function summary(array $cases):string{if(!$cases)return 'No actionable finding was produced from the currently available evidence.';$confirmed=count(array_filter($cases,static fn($c)=>$c['root_cause_status']==='confirmed'));return count($cases).' prioritized investigation(s); '.$confirmed.' confirmed directly by current account evidence.';}
    private static function direct(string $title):bool{return preg_match('/no active primary conversions|negative keyword conflict|disapproval|broken url/i',$title)===1;}
    private static function dataConfidence(array $f,array ...$modules):float{$available=count(array_filter($modules,static fn($m)=>!empty($m['available'])||!empty($m['account_diagnostic']['available'])));$sample=count((array)($modules[1]['terms']??[]))+count((array)($modules[3]['keywords']??[]));$base=.4+min(.32,$available*.08)+($sample>=30?.15:($sample>0?.05:-.1));if(in_array(($f['period']??''),['Current configuration','Last 180 days'],true))$base+=.08;return max(.25,min(.98,$base));}
    private static function hypotheses(string $title):array{if(stripos($title,'budget')!==false)return ['Budget capacity or shared-budget allocation is limiting delivery.','Search demand or rank—not budget—is the real constraint.','A recent change is still in its learning or ramp-up window.'];if(stripos($title,'conversion')!==false)return ['Conversion configuration changed or is incomplete.','Lead volume changed while tracking remains healthy.','Reporting lag or attribution differences affect the comparison.'];if(stripos($title,'keyword')!==false||stripos($title,'search')!==false)return ['Keyword or negative routing is blocking relevant demand.','The query/keyword has insufficient eligible search volume.','Campaign structure is causing traffic to match elsewhere.'];return ['A recent account change produced the observation.','Traffic quality or auction conditions changed.','Measurement or minimum-data limitations explain the apparent issue.'];}
    private static function rank(string $s):int{return ['critical'=>0,'warning'=>1,'opportunity'=>2,'healthy'=>3][$s]??9;}
    private static function history(array $finding,array $memories):array{$text=strtolower((string)($finding['title']??'').' '.(string)($finding['evidence']??''));$matched=[];foreach($memories as $memory){$subject=strtolower(trim((string)($memory['subject_key']??'')));if(($memory['memory_type']??'')==='client_rule'||($subject!==''&&str_contains($text,$subject)))$matched[]=['type'=>(string)$memory['memory_type'],'subject'=>(string)$memory['subject_key'],'content'=>(string)$memory['content'],'last_confirmed_at'=>(string)$memory['last_confirmed_at']];if(count($matched)>=5)break;}return $matched;}
}
