<?php
/**
 * Generic Elementor Draft Page Receiver
 *
 * Endpoint: POST /wp-json/wnq-agent/v1/create-elementor-page
 *
 * Creates editable Elementor draft pages on the connected client site from
 * Elementor JSON generated by the Golden Web Marketing SEO OS hub.
 *
 * @package Golden Web Marketing SEO Agent
 */

namespace WNQA;

if (!defined('ABSPATH')) {
    exit;
}

final class ElementorPageReceiver
{
    public static function register(): void
    {
        add_action('rest_api_init', [self::class, 'registerRoute']);
    }

    public static function registerRoute(): void
    {
        register_rest_route('wnq-agent/v1', '/create-elementor-page', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handleCreate'],
            'permission_callback' => [self::class, 'authenticate'],
        ]);
    }

    public static function authenticate(\WP_REST_Request $request)
    {
        $config = get_option('wnqa_config', []);
        $my_key = $config['api_key'] ?? '';

        if (empty($my_key)) {
            return new \WP_Error('not_configured', 'Agent plugin is not configured.', ['status' => 503]);
        }

        $sent_key = $request->get_header('X-WNQ-Api-Key') ?: ($request->get_param('api_key') ?? '');
        if (empty($sent_key) || !hash_equals($my_key, $sent_key)) {
            return new \WP_Error('invalid_api_key', 'Invalid API key.', ['status' => 403]);
        }

        return true;
    }

    public static function handleCreate(\WP_REST_Request $request)
    {
        try {
            return self::doCreate($request);
        } catch (\Throwable $e) {
            error_log('WNQ ElementorPageReceiver error: ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
            return new \WP_REST_Response([
                'error'   => $e->getMessage(),
                'context' => basename($e->getFile()) . ':' . $e->getLine(),
            ], 500);
        }
    }

    private static function doCreate(\WP_REST_Request $request)
    {
        $body = $request->get_json_params();
        if (!is_array($body)) {
            $body = [];
        }

        $title = sanitize_text_field($body['title'] ?? '');
        $title_tag = sanitize_text_field($body['title_tag'] ?? $title);
        $meta_desc = sanitize_textarea_field($body['meta_description'] ?? '');
        $h1 = sanitize_text_field($body['h1'] ?? $title);
        $focus_kw = sanitize_text_field($body['focus_keyword'] ?? $h1);
        $slug = sanitize_title($body['slug'] ?? '');
        $post_content = wp_kses_post($body['post_content'] ?? '');
        $featured_image_id = absint($body['featured_image_id'] ?? 0);
        $page_settings = isset($body['page_settings']) && is_array($body['page_settings'])
            ? $body['page_settings']
            : ['hide_title' => 'yes'];
        $elementor_raw = isset($body['elementor_data']) ? (string)$body['elementor_data'] : '';

        if ($title === '') {
            return new \WP_REST_Response(['error' => 'title is required'], 400);
        }
        if ($slug === '') {
            $slug = sanitize_title($title);
        }
        if ($elementor_raw === '') {
            return new \WP_REST_Response(['error' => 'elementor_data is required'], 400);
        }

        $elementor = json_decode($elementor_raw, true);
        if (!is_array($elementor)) {
            return new \WP_REST_Response(['error' => 'Invalid elementor_data JSON: ' . json_last_error_msg()], 400);
        }

        $slug = self::uniquePageSlug($slug);

        $saved_hooks = null;
        self::suspendSavePostHooks($saved_hooks);
        try {
            $page_id = wp_insert_post([
                'post_title'     => $title,
                'post_name'      => $slug,
                'post_content'   => $post_content,
                'post_excerpt'   => wp_strip_all_tags($meta_desc),
                'post_status'    => 'draft',
                'post_type'      => 'page',
                'comment_status' => 'closed',
                'ping_status'    => 'closed',
            ], true);
        } finally {
            self::restoreSavePostHooks($saved_hooks);
        }

        if (is_wp_error($page_id)) {
            return new \WP_REST_Response(['error' => $page_id->get_error_message()], 500);
        }

        $image_import = self::localizeElementorImages($elementor, (int)$page_id, $title);

        update_post_meta($page_id, '_elementor_edit_mode', 'builder');
        update_post_meta($page_id, '_elementor_template_type', 'wp-page');
        update_post_meta($page_id, '_elementor_version', defined('ELEMENTOR_VERSION') ? ELEMENTOR_VERSION : '3.0.0');
        update_post_meta($page_id, '_elementor_page_settings', $page_settings);
        update_post_meta($page_id, '_elementor_data', wp_slash(wp_json_encode($elementor, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)));
        update_post_meta($page_id, '_wnq_ai_elementor_builder', 1);
        update_post_meta($page_id, '_wnq_h1', $h1);
        update_post_meta($page_id, '_meta_description', $meta_desc);

        if ($featured_image_id > 0 && get_post_type($featured_image_id) === 'attachment') {
            set_post_thumbnail($page_id, $featured_image_id);
        } elseif (!empty($image_import['first_id'])) {
            set_post_thumbnail($page_id, (int)$image_import['first_id']);
        }

        self::saveSeoMeta((int)$page_id, $title_tag, $meta_desc, $focus_kw);
        self::clearElementorCache((int)$page_id);

        return new \WP_REST_Response([
            'status'        => 'draft_created',
            'page_id'       => (int)$page_id,
            'post_slug'     => $slug,
            'page_url'      => get_permalink($page_id),
            'preview_url'   => get_preview_post_link((int)$page_id) ?: get_permalink($page_id),
            'edit_url'      => admin_url('post.php?post=' . (int)$page_id . '&action=edit'),
            'elementor_url' => admin_url('post.php?post=' . (int)$page_id . '&action=elementor'),
            'pages_url'     => admin_url('edit.php?post_type=page'),
            'images_imported' => count((array)($image_import['imported'] ?? [])),
            'image_import_errors' => (array)($image_import['errors'] ?? []),
        ], 201);
    }

    private static function localizeElementorImages(array &$elementor, int $page_id, string $title): array
    {
        $cache = [];
        $result = [
            'imported' => [],
            'errors'   => [],
            'first_id' => 0,
        ];

        self::walkElementorImages($elementor, $page_id, $title, $cache, $result);

        return $result;
    }

    private static function walkElementorImages(&$value, int $page_id, string $title, array &$cache, array &$result): void
    {
        if (!is_array($value)) {
            return;
        }

        if (self::isElementorImageValue($value)) {
            $original_url = trim((string)($value['url'] ?? ''));
            if (self::shouldImportImageUrl($original_url)) {
                if (!array_key_exists($original_url, $cache)) {
                    $cache[$original_url] = self::sideloadRemoteImage($original_url, $page_id, $title);
                }

                $import = $cache[$original_url];
                if (is_array($import) && !empty($import['id']) && !empty($import['url'])) {
                    $value['id'] = (int)$import['id'];
                    $value['url'] = (string)$import['url'];
                    if (array_key_exists('source', $value)) {
                        $value['source'] = 'library';
                    }
                    if (!$result['first_id']) {
                        $result['first_id'] = (int)$import['id'];
                    }
                    $result['imported'][self::imageResultKey($original_url)] = $import;
                } elseif (is_string($import) && $import !== '') {
                    $result['errors'][self::imageResultKey($original_url)] = $import;
                }
            }
        }

        foreach ($value as &$child) {
            if (is_array($child)) {
                self::walkElementorImages($child, $page_id, $title, $cache, $result);
            }
        }
        unset($child);
    }

    private static function isElementorImageValue(array $value): bool
    {
        if (!array_key_exists('url', $value) || !is_string($value['url'])) {
            return false;
        }

        // Link controls also contain a "url" key. Image controls have an id/source/alt/size shape.
        if (array_key_exists('is_external', $value) || array_key_exists('nofollow', $value) || array_key_exists('custom_attributes', $value)) {
            return false;
        }

        return array_key_exists('id', $value)
            || array_key_exists('source', $value)
            || array_key_exists('alt', $value)
            || array_key_exists('size', $value);
    }

    private static function shouldImportImageUrl(string $url): bool
    {
        if ($url === '' || strpos($url, '{{') !== false) {
            return false;
        }

        if (self::isDataImageUri($url)) {
            return true;
        }

        if (!preg_match('#^https?://#i', $url)) {
            return false;
        }

        $source_host = strtolower((string)parse_url($url, PHP_URL_HOST));
        $site_host = strtolower((string)parse_url(home_url('/'), PHP_URL_HOST));
        if ($source_host !== '' && $site_host !== '' && $source_host === $site_host) {
            return false;
        }

        return true;
    }

    private static function sideloadRemoteImage(string $url, int $page_id, string $title)
    {
        if (self::isDataImageUri($url)) {
            return self::sideloadDataImage($url, $page_id, $title);
        }

        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        $tmp = self::downloadUrlAllowingConfiguredHubHost($url);
        if (is_wp_error($tmp)) {
            return $tmp->get_error_message();
        }

        $mime = self::detectImageMime((string)$tmp);
        if ($mime === '') {
            @unlink((string)$tmp);
            return 'Downloaded file was not a supported image.';
        }

        $ext = self::extensionForMime($mime);
        $filename = sanitize_file_name(sanitize_title($title ?: 'elementor-image') . '-' . substr(md5($url), 0, 10) . '.' . $ext);
        $file = [
            'name'     => $filename,
            'type'     => $mime,
            'tmp_name' => (string)$tmp,
            'error'    => 0,
            'size'     => filesize((string)$tmp) ?: 0,
        ];

        $attachment_id = media_handle_sideload($file, $page_id, $title);
        if (is_wp_error($attachment_id)) {
            @unlink((string)$tmp);
            return $attachment_id->get_error_message();
        }

        update_post_meta((int)$attachment_id, '_wp_attachment_image_alt', $title);

        $local_url = wp_get_attachment_url((int)$attachment_id);
        if (!$local_url) {
            return 'Image imported, but WordPress did not return an attachment URL.';
        }

        return [
            'id'  => (int)$attachment_id,
            'url' => esc_url_raw($local_url),
        ];
    }

    private static function downloadUrlAllowingConfiguredHubHost(string $url)
    {
        $source_host = strtolower((string)parse_url($url, PHP_URL_HOST));
        $config = get_option('wnqa_config', []);
        $hub_host = strtolower((string)parse_url((string)($config['hub_url'] ?? ''), PHP_URL_HOST));
        $allow_hub_host = null;

        if ($source_host !== '' && $hub_host !== '' && $source_host === $hub_host) {
            $allow_hub_host = static function ($is_external, $host) use ($hub_host) {
                return strtolower((string)$host) === $hub_host ? true : $is_external;
            };
            add_filter('http_request_host_is_external', $allow_hub_host, 10, 2);
        }

        try {
            return download_url($url, 45);
        } finally {
            if ($allow_hub_host) {
                remove_filter('http_request_host_is_external', $allow_hub_host, 10);
            }
        }
    }

    private static function isDataImageUri(string $url): bool
    {
        return preg_match('#^data:image/(?:jpeg|jpg|png|gif|webp);base64,#i', $url) === 1;
    }

    private static function imageResultKey(string $url): string
    {
        if (self::isDataImageUri($url)) {
            return 'uploaded-image-' . substr(md5($url), 0, 10);
        }

        return $url;
    }

    private static function sideloadDataImage(string $data_uri, int $page_id, string $title)
    {
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        if (!preg_match('#^data:(image/(?:jpeg|jpg|png|gif|webp));base64,(.+)$#is', $data_uri, $matches)) {
            return 'Uploaded image data was not a supported image.';
        }

        $mime = strtolower($matches[1]);
        if ($mime === 'image/jpg') {
            $mime = 'image/jpeg';
        }

        $binary = base64_decode(preg_replace('/\s+/', '', (string)$matches[2]), true);
        if (!is_string($binary) || $binary === '') {
            return 'Uploaded image data could not be decoded.';
        }

        if (strlen($binary) > 5 * 1024 * 1024) {
            return 'Uploaded image must be 5 MB or smaller.';
        }

        $ext = self::extensionForMime($mime);
        $tmp = wp_tempnam('wnq-elementor-image.' . $ext);
        if (!$tmp) {
            return 'Could not create a temporary file for uploaded image.';
        }

        if (file_put_contents($tmp, $binary) === false) {
            @unlink($tmp);
            return 'Could not write uploaded image to a temporary file.';
        }

        $detected = self::detectImageMime((string)$tmp);
        if ($detected === '') {
            @unlink($tmp);
            return 'Uploaded file was not a supported image.';
        }

        $filename = sanitize_file_name(sanitize_title($title ?: 'elementor-image') . '-' . substr(md5($data_uri), 0, 10) . '.' . self::extensionForMime($detected));
        $file = [
            'name'     => $filename,
            'type'     => $detected,
            'tmp_name' => (string)$tmp,
            'error'    => 0,
            'size'     => filesize((string)$tmp) ?: 0,
        ];

        $attachment_id = media_handle_sideload($file, $page_id, $title);
        if (is_wp_error($attachment_id)) {
            @unlink((string)$tmp);
            return $attachment_id->get_error_message();
        }

        update_post_meta((int)$attachment_id, '_wp_attachment_image_alt', $title);

        $local_url = wp_get_attachment_url((int)$attachment_id);
        if (!$local_url) {
            return 'Image imported, but WordPress did not return an attachment URL.';
        }

        return [
            'id'  => (int)$attachment_id,
            'url' => esc_url_raw($local_url),
        ];
    }

    private static function detectImageMime(string $file): string
    {
        $mime = '';
        if (function_exists('wp_get_image_mime')) {
            $mime = (string)wp_get_image_mime($file);
        }

        if ($mime === '' && function_exists('getimagesize')) {
            $size = @getimagesize($file);
            if (is_array($size) && !empty($size['mime'])) {
                $mime = (string)$size['mime'];
            }
        }

        $allowed = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
        return in_array($mime, $allowed, true) ? $mime : '';
    }

    private static function extensionForMime(string $mime): string
    {
        $map = [
            'image/jpeg' => 'jpg',
            'image/png'  => 'png',
            'image/gif'  => 'gif',
            'image/webp' => 'webp',
        ];

        return $map[$mime] ?? 'jpg';
    }

    private static function uniquePageSlug(string $base_slug): string
    {
        global $wpdb;

        $base_slug = $base_slug ?: 'ai-elementor-draft';
        $candidate = $base_slug;
        $index = 2;

        while ((int)$wpdb->get_var(
            $wpdb->prepare(
                "SELECT ID FROM {$wpdb->posts}
                 WHERE post_type='page' AND post_name=%s AND post_status NOT IN ('trash','auto-draft')
                 LIMIT 1",
                $candidate
            )
        )) {
            $candidate = $base_slug . '-' . $index;
            $index++;
        }

        return $candidate;
    }

    private static function saveSeoMeta(int $page_id, string $title_tag, string $meta_desc, string $focus_kw): void
    {
        if (defined('WPSEO_VERSION')) {
            update_post_meta($page_id, '_yoast_wpseo_title', $title_tag);
            update_post_meta($page_id, '_yoast_wpseo_metadesc', $meta_desc);
            if ($focus_kw !== '') {
                update_post_meta($page_id, '_yoast_wpseo_focuskw', $focus_kw);
            }
        }

        if (defined('RANK_MATH_VERSION') || class_exists('RankMath') || function_exists('rank_math')) {
            update_post_meta($page_id, 'rank_math_title', $title_tag);
            update_post_meta($page_id, 'rank_math_description', $meta_desc);
            if ($focus_kw !== '') {
                update_post_meta($page_id, 'rank_math_focus_keyword', $focus_kw);
            }
        }
    }

    private static function clearElementorCache(int $page_id): void
    {
        delete_post_meta($page_id, '_elementor_css');
        clean_post_cache($page_id);

        try {
            if (class_exists('\Elementor\Core\Files\CSS\Post')) {
                $post_css = new \Elementor\Core\Files\CSS\Post($page_id);
                if (method_exists($post_css, 'delete')) {
                    $post_css->delete();
                }
            }

            if (class_exists('\Elementor\Plugin')) {
                $plugin = \Elementor\Plugin::$instance;
                if (isset($plugin->files_manager) && method_exists($plugin->files_manager, 'clear_cache')) {
                    $plugin->files_manager->clear_cache();
                }
            }
        } catch (\Throwable $e) {
            // Cache cleanup should not block draft creation.
        }
    }

    private static function suspendSavePostHooks(&$snapshot): void
    {
        global $wp_filter;
        $snapshot = [];
        foreach (['save_post', 'save_post_page', 'edit_post', 'post_updated', 'wp_after_insert_post', 'wp_insert_post'] as $hook) {
            if (isset($wp_filter[$hook])) {
                $snapshot[$hook] = $wp_filter[$hook];
                unset($wp_filter[$hook]);
            }
        }
    }

    private static function restoreSavePostHooks(&$snapshot): void
    {
        global $wp_filter;
        foreach ((array)$snapshot as $hook => $hook_obj) {
            $wp_filter[$hook] = $hook_obj;
        }
        $snapshot = null;
    }
}
