<?php
/**
 * Generic Elementor Draft Page Receiver
 *
 * Endpoint: POST /wp-json/wnq-agent/v1/create-elementor-page
 *
 * Creates editable Elementor draft pages on the connected client site from
 * Elementor JSON generated by the Golden Web Marketing SEO OS hub.
 *
 * @package Golden Web Marketing SEO Agent
 */

namespace WNQA;

if (!defined('ABSPATH')) {
    exit;
}

final class ElementorPageReceiver
{
    public static function register(): void
    {
        add_action('rest_api_init', [self::class, 'registerRoute']);
    }

    public static function registerRoute(): void
    {
        register_rest_route('wnq-agent/v1', '/create-elementor-page', [
            'methods'             => 'POST',
            'callback'            => [self::class, 'handleCreate'],
            'permission_callback' => [self::class, 'authenticate'],
        ]);
    }

    public static function authenticate(\WP_REST_Request $request)
    {
        $config = get_option('wnqa_config', []);
        $my_key = $config['api_key'] ?? '';

        if (empty($my_key)) {
            return new \WP_Error('not_configured', 'Agent plugin is not configured.', ['status' => 503]);
        }

        $sent_key = $request->get_header('X-WNQ-Api-Key') ?: ($request->get_param('api_key') ?? '');
        if (empty($sent_key) || !hash_equals($my_key, $sent_key)) {
            return new \WP_Error('invalid_api_key', 'Invalid API key.', ['status' => 403]);
        }

        return true;
    }

    public static function handleCreate(\WP_REST_Request $request)
    {
        try {
            return self::doCreate($request);
        } catch (\Throwable $e) {
            error_log('WNQ ElementorPageReceiver error: ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
            return new \WP_REST_Response([
                'error'   => $e->getMessage(),
                'context' => basename($e->getFile()) . ':' . $e->getLine(),
            ], 500);
        }
    }

    private static function doCreate(\WP_REST_Request $request)
    {
        $body = $request->get_json_params();
        if (!is_array($body)) {
            $body = [];
        }

        $title = sanitize_text_field($body['title'] ?? '');
        $title_tag = sanitize_text_field($body['title_tag'] ?? $title);
        $meta_desc = sanitize_textarea_field($body['meta_description'] ?? '');
        $h1 = sanitize_text_field($body['h1'] ?? $title);
        $focus_kw = sanitize_text_field($body['focus_keyword'] ?? $h1);
        $slug = sanitize_title($body['slug'] ?? '');
        $post_content = wp_kses_post($body['post_content'] ?? '');
        $featured_image_id = absint($body['featured_image_id'] ?? 0);
        $page_settings = isset($body['page_settings']) && is_array($body['page_settings'])
            ? $body['page_settings']
            : ['hide_title' => 'yes'];
        $elementor_raw = isset($body['elementor_data']) ? (string)$body['elementor_data'] : '';

        if ($title === '') {
            return new \WP_REST_Response(['error' => 'title is required'], 400);
        }
        if ($slug === '') {
            $slug = sanitize_title($title);
        }
        if ($elementor_raw === '') {
            return new \WP_REST_Response(['error' => 'elementor_data is required'], 400);
        }

        $elementor = json_decode($elementor_raw, true);
        if (!is_array($elementor)) {
            return new \WP_REST_Response(['error' => 'Invalid elementor_data JSON: ' . json_last_error_msg()], 400);
        }

        $slug = self::uniquePageSlug($slug);

        $saved_hooks = null;
        self::suspendSavePostHooks($saved_hooks);
        try {
            $page_id = wp_insert_post([
                'post_title'     => $title,
                'post_name'      => $slug,
                'post_content'   => $post_content,
                'post_excerpt'   => wp_strip_all_tags($meta_desc),
                'post_status'    => 'draft',
                'post_type'      => 'page',
                'comment_status' => 'closed',
                'ping_status'    => 'closed',
            ], true);
        } finally {
            self::restoreSavePostHooks($saved_hooks);
        }

        if (is_wp_error($page_id)) {
            return new \WP_REST_Response(['error' => $page_id->get_error_message()], 500);
        }

        update_post_meta($page_id, '_elementor_edit_mode', 'builder');
        update_post_meta($page_id, '_elementor_template_type', 'wp-page');
        update_post_meta($page_id, '_elementor_version', defined('ELEMENTOR_VERSION') ? ELEMENTOR_VERSION : '3.0.0');
        update_post_meta($page_id, '_elementor_page_settings', $page_settings);
        update_post_meta($page_id, '_elementor_data', wp_slash(wp_json_encode($elementor, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)));
        update_post_meta($page_id, '_wnq_ai_elementor_builder', 1);
        update_post_meta($page_id, '_wnq_h1', $h1);
        update_post_meta($page_id, '_meta_description', $meta_desc);

        if ($featured_image_id > 0 && get_post_type($featured_image_id) === 'attachment') {
            set_post_thumbnail($page_id, $featured_image_id);
        }

        self::saveSeoMeta((int)$page_id, $title_tag, $meta_desc, $focus_kw);
        self::clearElementorCache((int)$page_id);

        return new \WP_REST_Response([
            'status'        => 'draft_created',
            'page_id'       => (int)$page_id,
            'post_slug'     => $slug,
            'page_url'      => get_permalink($page_id),
            'preview_url'   => get_preview_post_link((int)$page_id) ?: get_permalink($page_id),
            'edit_url'      => admin_url('post.php?post=' . (int)$page_id . '&action=edit'),
            'elementor_url' => admin_url('post.php?post=' . (int)$page_id . '&action=elementor'),
            'pages_url'     => admin_url('edit.php?post_type=page'),
        ], 201);
    }

    private static function uniquePageSlug(string $base_slug): string
    {
        global $wpdb;

        $base_slug = $base_slug ?: 'ai-elementor-draft';
        $candidate = $base_slug;
        $index = 2;

        while ((int)$wpdb->get_var(
            $wpdb->prepare(
                "SELECT ID FROM {$wpdb->posts}
                 WHERE post_type='page' AND post_name=%s AND post_status NOT IN ('trash','auto-draft')
                 LIMIT 1",
                $candidate
            )
        )) {
            $candidate = $base_slug . '-' . $index;
            $index++;
        }

        return $candidate;
    }

    private static function saveSeoMeta(int $page_id, string $title_tag, string $meta_desc, string $focus_kw): void
    {
        if (defined('WPSEO_VERSION')) {
            update_post_meta($page_id, '_yoast_wpseo_title', $title_tag);
            update_post_meta($page_id, '_yoast_wpseo_metadesc', $meta_desc);
            if ($focus_kw !== '') {
                update_post_meta($page_id, '_yoast_wpseo_focuskw', $focus_kw);
            }
        }

        if (defined('RANK_MATH_VERSION') || class_exists('RankMath') || function_exists('rank_math')) {
            update_post_meta($page_id, 'rank_math_title', $title_tag);
            update_post_meta($page_id, 'rank_math_description', $meta_desc);
            if ($focus_kw !== '') {
                update_post_meta($page_id, 'rank_math_focus_keyword', $focus_kw);
            }
        }
    }

    private static function clearElementorCache(int $page_id): void
    {
        delete_post_meta($page_id, '_elementor_css');
        clean_post_cache($page_id);

        try {
            if (class_exists('\Elementor\Core\Files\CSS\Post')) {
                $post_css = new \Elementor\Core\Files\CSS\Post($page_id);
                if (method_exists($post_css, 'delete')) {
                    $post_css->delete();
                }
            }

            if (class_exists('\Elementor\Plugin')) {
                $plugin = \Elementor\Plugin::$instance;
                if (isset($plugin->files_manager) && method_exists($plugin->files_manager, 'clear_cache')) {
                    $plugin->files_manager->clear_cache();
                }
            }
        } catch (\Throwable $e) {
            // Cache cleanup should not block draft creation.
        }
    }

    private static function suspendSavePostHooks(&$snapshot): void
    {
        global $wp_filter;
        $snapshot = [];
        foreach (['save_post', 'save_post_page', 'edit_post', 'post_updated', 'wp_after_insert_post', 'wp_insert_post'] as $hook) {
            if (isset($wp_filter[$hook])) {
                $snapshot[$hook] = $wp_filter[$hook];
                unset($wp_filter[$hook]);
            }
        }
    }

    private static function restoreSavePostHooks(&$snapshot): void
    {
        global $wp_filter;
        foreach ((array)$snapshot as $hook => $hook_obj) {
            $wp_filter[$hook] = $hook_obj;
        }
        $snapshot = null;
    }
}
